# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'license.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class License_Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(405, 135)
        self.li_machinenumber = QtWidgets.QLineEdit(Widget)
        self.li_machinenumber.setGeometry(QtCore.QRect(140, 30, 251, 25))
        self.li_machinenumber.setObjectName("li_machinenumber")
        self.li_serialnumber = QtWidgets.QLineEdit(Widget)
        self.li_serialnumber.setGeometry(QtCore.QRect(140, 60, 251, 25))
        self.li_serialnumber.setObjectName("li_serialnumber")
        self.label_machinenumber = QtWidgets.QLabel(Widget)
        self.label_machinenumber.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.label_machinenumber.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_machinenumber.setObjectName("label_machinenumber")
        self.label_serialnumber = QtWidgets.QLabel(Widget)
        self.label_serialnumber.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_serialnumber.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_serialnumber.setObjectName("label_serialnumber")
        self.btn_licience_yes = QtWidgets.QPushButton(Widget)
        self.btn_licience_yes.setGeometry(QtCore.QRect(0, 100, 201, 23))
        self.btn_licience_yes.setObjectName("btn_licience_yes")
        self.btn_licience_no = QtWidgets.QPushButton(Widget)
        self.btn_licience_no.setGeometry(QtCore.QRect(200, 100, 201, 23))
        self.btn_licience_no.setObjectName("btn_licience_no")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_machinenumber.setText(_translate("Widget", "機械番号"))
        self.label_serialnumber.setText(_translate("Widget", "シリアルナンバー"))
        self.btn_licience_yes.setText(_translate("Widget", "接続"))
        self.btn_licience_no.setText(_translate("Widget", "近い"))
