# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qoo_user_infor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Login_Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(555, 241)
        self.li_key = QtWidgets.QLineEdit(Widget)
        self.li_key.setGeometry(QtCore.QRect(200, 150, 251, 31))
        self.li_key.setObjectName("li_key")
        self.li_userid = QtWidgets.QLineEdit(Widget)
        self.li_userid.setGeometry(QtCore.QRect(200, 70, 251, 31))
        self.li_userid.setObjectName("li_userid")
        self.label_machinenumber = QtWidgets.QLabel(Widget)
        self.label_machinenumber.setGeometry(QtCore.QRect(50, 150, 111, 31))
        self.label_machinenumber.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_machinenumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_machinenumber.setObjectName("label_machinenumber")
        self.label_serialnumber = QtWidgets.QLabel(Widget)
        self.label_serialnumber.setGeometry(QtCore.QRect(50, 70, 111, 31))
        self.label_serialnumber.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_serialnumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_serialnumber.setObjectName("label_serialnumber")
        self.btn_log_yes = QtWidgets.QPushButton(Widget)
        self.btn_log_yes.setGeometry(QtCore.QRect(40, 200, 201, 31))
        self.btn_log_yes.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.btn_log_yes.setObjectName("btn_log_yes")
        self.btn_log_no = QtWidgets.QPushButton(Widget)
        self.btn_log_no.setGeometry(QtCore.QRect(310, 200, 201, 31))
        self.btn_log_no.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.btn_log_no.setObjectName("btn_log_no")
        self.label_alert = QtWidgets.QLabel(Widget)
        self.label_alert.setGeometry(QtCore.QRect(160, 50, 47, 13))
        self.label_alert.setText("")
        self.label_alert.setObjectName("label_alert")
        self.li_password = QtWidgets.QLineEdit(Widget)
        self.li_password.setGeometry(QtCore.QRect(200, 110, 251, 31))
        self.li_password.setObjectName("li_password")
        self.label_serialnumber_2 = QtWidgets.QLabel(Widget)
        self.label_serialnumber_2.setGeometry(QtCore.QRect(50, 110, 111, 31))
        self.label_serialnumber_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_serialnumber_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_serialnumber_2.setObjectName("label_serialnumber_2")
        self.label_user_info = QtWidgets.QLabel(Widget)
        self.label_user_info.setGeometry(QtCore.QRect(150, 10, 251, 41))
        self.label_user_info.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_user_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_user_info.setObjectName("label_user_info")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_machinenumber.setText(_translate("Widget", "鍵"))
        self.label_serialnumber.setText(_translate("Widget", "ユーザー識別"))
        self.btn_log_yes.setText(_translate("Widget", "確認"))
        self.btn_log_no.setText(_translate("Widget", "近い"))
        self.label_serialnumber_2.setText(_translate("Widget", "パスワード"))
        self.label_user_info.setText(_translate("Widget", "ユーザー情報"))
