# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Aliex_UI-1.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QMovie


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1260, 694)
        Widget.setBaseSize(QtCore.QSize(100, 10))
        self.wid_amazon = QtWidgets.QWidget(Widget)
        self.wid_amazon.setGeometry(QtCore.QRect(30, 160, 1211, 441))
        self.wid_amazon.setObjectName("wid_amazon")
        self.tableWidget_amazon = QtWidgets.QTableWidget(self.wid_amazon)
        self.tableWidget_amazon.setGeometry(QtCore.QRect(10, 20, 1191, 421))
        self.tableWidget_amazon.setObjectName("tableWidget_amazon")
        self.tableWidget_amazon.setColumnCount(5)
        self.tableWidget_amazon.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_amazon.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_amazon.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_amazon.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_amazon.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_amazon.setHorizontalHeaderItem(4, item)
        self.stackedWidget = QtWidgets.QStackedWidget(Widget)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 620, 1191, 80))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_amazon = QtWidgets.QWidget()
        self.page_amazon.setObjectName("page_amazon")
        self.btn_get = QtWidgets.QPushButton(self.page_amazon)
        self.btn_get.setGeometry(QtCore.QRect(0, 20, 391, 41))
        self.btn_get.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(138, 5, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_get.setObjectName("btn_get")
        self.btn_compare = QtWidgets.QPushButton(self.page_amazon)
        self.btn_compare.setGeometry(QtCore.QRect(770, 20, 421, 41))
        self.btn_compare.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(138, 5, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_compare.setObjectName("btn_compare")
        self.btn_get2 = QtWidgets.QPushButton(self.page_amazon)
        self.btn_get2.setGeometry(QtCore.QRect(350, 20, 421, 41))
        self.btn_get2.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(138, 5, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_get2.setObjectName("btn_get2")
        self.stackedWidget.addWidget(self.page_amazon)
        self.page_qoo = QtWidgets.QWidget()
        self.page_qoo.setObjectName("page_qoo")
        self.lineEdit_rate = QtWidgets.QLineEdit(self.page_qoo)
        self.lineEdit_rate.setGeometry(QtCore.QRect(30, 30, 121, 21))
        self.lineEdit_rate.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_rate.setObjectName("lineEdit_rate")
        self.btn_rate = QtWidgets.QPushButton(self.page_qoo)
        self.btn_rate.setGeometry(QtCore.QRect(160, 20, 91, 41))
        self.btn_rate.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(0,0,117);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_rate.setObjectName("btn_rate")
        self.btn_new = QtWidgets.QPushButton(self.page_qoo)
        self.btn_new.setGeometry(QtCore.QRect(0, 20, 321, 41))
        self.btn_new.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(138, 5, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_new.setObjectName("btn_new")
        self.btn_update = QtWidgets.QPushButton(self.page_qoo)
        self.btn_update.setGeometry(QtCore.QRect(320, 20, 301, 41))
        self.btn_update.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(138, 5, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_update.setObjectName("btn_update")
        self.btn_remove = QtWidgets.QPushButton(self.page_qoo)
        self.btn_remove.setGeometry(QtCore.QRect(620, 20, 291, 41))
        self.btn_remove.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(138, 5, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_remove.setObjectName("btn_remove")
        self.btn_start = QtWidgets.QPushButton(self.page_qoo)
        self.btn_start.setGeometry(QtCore.QRect(910, 20, 281, 41))
        self.btn_start.setStyleSheet("QPushButton{\n"
"\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(138, 5, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_start.setObjectName("btn_start")
        self.stackedWidget.addWidget(self.page_qoo)
        self.page_rakuten = QtWidgets.QWidget()
        self.page_rakuten.setObjectName("page_rakuten")
        self.stackedWidget.addWidget(self.page_rakuten)
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(0, -70, 1281, 231))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_raku = QtWidgets.QPushButton(self.groupBox)
        self.btn_raku.setGeometry(QtCore.QRect(510, 160, 201, 51))
        self.btn_raku.setAutoFillBackground(False)
        self.btn_raku.setStyleSheet("QPushButton{\n"
"    border-image: url(img/rakuten.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_raku.setText("")
        self.btn_raku.setObjectName("btn_raku")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(470, 80, 321, 61))
        self.label.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 36pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_raku = QtWidgets.QLabel(self.groupBox)
        self.label_raku.setGeometry(QtCore.QRect(510, 220, 201, 6))
        self.label_raku.setBaseSize(QtCore.QSize(0, 0))
        self.label_raku.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_raku.setText("")
        self.label_raku.setObjectName("label_raku")
        self.btn_amazon = QtWidgets.QPushButton(self.groupBox)
        self.btn_amazon.setGeometry(QtCore.QRect(60, 160, 201, 51))
        self.btn_amazon.setStyleSheet("QPushButton{\n"
"\n"
"    border-image: url(img/amazon.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_amazon.setText("")
        self.btn_amazon.setObjectName("btn_amazon")
        self.label_qoo = QtWidgets.QLabel(self.groupBox)
        self.label_qoo.setGeometry(QtCore.QRect(280, 220, 211, 6))
        self.label_qoo.setBaseSize(QtCore.QSize(0, 0))
        self.label_qoo.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_qoo.setText("")
        self.label_qoo.setObjectName("label_qoo")
        self.btn_qoo = QtWidgets.QPushButton(self.groupBox)
        self.btn_qoo.setGeometry(QtCore.QRect(280, 160, 211, 51))
        self.btn_qoo.setStyleSheet("QPushButton{\n"
"    border-image: url(img/qoo.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:yellow;\n"
"}")
        self.btn_qoo.setText("")
        self.btn_qoo.setObjectName("btn_qoo")
        self.label_amazon = QtWidgets.QLabel(self.groupBox)
        self.label_amazon.setGeometry(QtCore.QRect(60, 220, 201, 6))
        self.label_amazon.setBaseSize(QtCore.QSize(0, 0))
        self.label_amazon.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_amazon.setText("")
        self.label_amazon.setObjectName("label_amazon")
        self.btn_hide = QtWidgets.QPushButton(self.groupBox)
        self.btn_hide.setGeometry(QtCore.QRect(1080, 90, 31, 31))
        self.btn_hide.setStyleSheet("QPushButton{\n"
"    border-image: url(img/hide.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-image: url(img/hover_hide.png);\n"
"}\n"
"\n"
"")
        self.btn_hide.setText("")
        self.btn_hide.setObjectName("btn_hide")
        self.btn_close = QtWidgets.QPushButton(self.groupBox)
        self.btn_close.setGeometry(QtCore.QRect(1130, 90, 31, 31))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    border-image: url(img/close.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-image: url(img/hover_close.png);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.wid_qoo = QtWidgets.QWidget(Widget)
        self.wid_qoo.setGeometry(QtCore.QRect(30, 160, 1211, 441))
        self.wid_qoo.setObjectName("wid_qoo")
        self.tableWidget_qoo = QtWidgets.QTableWidget(self.wid_qoo)
        self.tableWidget_qoo.setGeometry(QtCore.QRect(10, 20, 1191, 421))
        self.tableWidget_qoo.setObjectName("tableWidget_qoo")
        self.tableWidget_qoo.setColumnCount(5)
        self.tableWidget_qoo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qoo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qoo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qoo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qoo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_qoo.setHorizontalHeaderItem(4, item)
        self.wid_raku = QtWidgets.QWidget(Widget)
        self.wid_raku.setGeometry(QtCore.QRect(30, 160, 1211, 441))
        self.wid_raku.setObjectName("wid_raku")
        self.tableWidget_raku = QtWidgets.QTableWidget(self.wid_raku)
        self.tableWidget_raku.setGeometry(QtCore.QRect(10, 20, 1191, 421))
        self.tableWidget_raku.setObjectName("tableWidget_raku")
        self.tableWidget_raku.setColumnCount(5)
        self.tableWidget_raku.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_raku.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_raku.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_raku.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_raku.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_raku.setHorizontalHeaderItem(4, item)
        self.label_loading = QtWidgets.QLabel(Widget)
        self.label_loading.setGeometry(QtCore.QRect(600, 300, 101, 91))
        self.label_loading.setText("werwer")
        self.label_loading.setObjectName("label_loading")
        # self.label_loading.setStyleSheet('border-image: url(img/loading.gif)')
        # self.movie = QMovie('img/loading.gif')
        # self.label.setMovie(self.movie)
        # self.movie.start()

        self.retranslateUi(Widget)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        item = self.tableWidget_amazon.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "画像"))
        item = self.tableWidget_amazon.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "タイトル"))
        item = self.tableWidget_amazon.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "価格"))
        item = self.tableWidget_amazon.horizontalHeaderItem(3)
        item.setText(_translate("Widget", "在庫"))
        item = self.tableWidget_amazon.horizontalHeaderItem(4)
        item.setText(_translate("Widget", "ID"))
        self.btn_get.setText(_translate("Widget", "新しく 抽出"))
        self.btn_compare.setText(_translate("Widget", "抽出 比較"))
        self.btn_get2.setText(_translate("Widget", "抽出"))
        self.btn_rate.setText(_translate("Widget", "設定"))
        self.btn_new.setText(_translate("Widget", "新規"))
        self.btn_update.setText(_translate("Widget", "更新"))
        self.btn_remove.setText(_translate("Widget", "消去"))
        self.btn_start.setText(_translate("Widget", "スタート"))
        self.label.setText(_translate("Widget", "管理ツール"))
        item = self.tableWidget_qoo.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "画像"))
        item = self.tableWidget_qoo.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "タイトル"))
        item = self.tableWidget_qoo.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "価格"))
        item = self.tableWidget_qoo.horizontalHeaderItem(3)
        item.setText(_translate("Widget", "在庫"))
        item = self.tableWidget_qoo.horizontalHeaderItem(4)
        item.setText(_translate("Widget", "ID"))
        item = self.tableWidget_raku.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "画像"))
        item = self.tableWidget_raku.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "タイトル"))
        item = self.tableWidget_raku.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "価格"))
        item = self.tableWidget_raku.horizontalHeaderItem(3)
        item.setText(_translate("Widget", "在庫"))
        item = self.tableWidget_raku.horizontalHeaderItem(4)
        item.setText(_translate("Widget", "ID"))
