# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(792, 316)
        self.li_machinenumber = QtWidgets.QLineEdit(Widget)
        self.li_machinenumber.setGeometry(QtCore.QRect(180, 110, 301, 31))
        self.li_machinenumber.setObjectName("li_machinenumber")
        self.li_serialnumber = QtWidgets.QLineEdit(Widget)
        self.li_serialnumber.setGeometry(QtCore.QRect(180, 160, 301, 31))
        self.li_serialnumber.setObjectName("li_serialnumber")
        self.label_machinenumber = QtWidgets.QLabel(Widget)
        self.label_machinenumber.setGeometry(QtCore.QRect(10, 110, 131, 21))
        self.label_machinenumber.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_machinenumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_machinenumber.setObjectName("label_machinenumber")
        self.label_serialnumber = QtWidgets.QLabel(Widget)
        self.label_serialnumber.setGeometry(QtCore.QRect(20, 160, 121, 21))
        self.label_serialnumber.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_serialnumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_serialnumber.setObjectName("label_serialnumber")
        self.btn_licience_yes = QtWidgets.QPushButton(Widget)
        self.btn_licience_yes.setGeometry(QtCore.QRect(80, 240, 231, 41))
        self.btn_licience_yes.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.btn_licience_yes.setObjectName("btn_licience_yes")
        self.btn_licience_no = QtWidgets.QPushButton(Widget)
        self.btn_licience_no.setGeometry(QtCore.QRect(450, 240, 231, 41))
        self.btn_licience_no.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.btn_licience_no.setObjectName("btn_licience_no")
        self.label_alert = QtWidgets.QLabel(Widget)
        self.label_alert.setGeometry(QtCore.QRect(250, 30, 311, 41))
        self.label_alert.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_alert.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_alert.setObjectName("label_alert")
        self.li_year = QtWidgets.QLineEdit(Widget)
        self.li_year.setGeometry(QtCore.QRect(600, 100, 121, 31))
        self.li_year.setText("")
        self.li_year.setObjectName("li_year")
        self.li_month = QtWidgets.QLineEdit(Widget)
        self.li_month.setGeometry(QtCore.QRect(600, 140, 121, 31))
        self.li_month.setText("")
        self.li_month.setObjectName("li_month")
        self.li_day = QtWidgets.QLineEdit(Widget)
        self.li_day.setGeometry(QtCore.QRect(600, 180, 121, 31))
        self.li_day.setText("")
        self.li_day.setObjectName("li_day")
        self.label_machinenumber_2 = QtWidgets.QLabel(Widget)
        self.label_machinenumber_2.setGeometry(QtCore.QRect(540, 110, 51, 21))
        self.label_machinenumber_2.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_machinenumber_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_machinenumber_2.setObjectName("label_machinenumber_2")
        self.label_machinenumber_3 = QtWidgets.QLabel(Widget)
        self.label_machinenumber_3.setGeometry(QtCore.QRect(540, 140, 51, 31))
        self.label_machinenumber_3.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_machinenumber_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_machinenumber_3.setObjectName("label_machinenumber_3")
        self.label_machinenumber_4 = QtWidgets.QLabel(Widget)
        self.label_machinenumber_4.setGeometry(QtCore.QRect(540, 180, 51, 31))
        self.label_machinenumber_4.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_machinenumber_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_machinenumber_4.setObjectName("label_machinenumber_4")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_machinenumber.setText(_translate("Widget", "機械番号"))
        self.label_serialnumber.setText(_translate("Widget", "シリアルナンバー"))
        self.btn_licience_yes.setText(_translate("Widget", "生成"))
        self.btn_licience_no.setText(_translate("Widget", "近い"))
        self.label_alert.setText(_translate("Widget", "生成キー"))
        self.label_machinenumber_2.setText(_translate("Widget", "年"))
        self.label_machinenumber_3.setText(_translate("Widget", "月"))
        self.label_machinenumber_4.setText(_translate("Widget", "日"))
